package logger;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "Events")
public class Event {

    @Id
    private EventId eventId;

    private String entry;

    public Event() {
        // Default constructor is required by AWS DynamoDB SDK
    }

    public Event(String entry, EventId eventId) {
        this.entry = entry;
        this.eventId = eventId;
    }

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return eventId != null ? eventId.getId() : null;
    }

    public void setId(String id) {
        if (eventId == null) {
            eventId = new EventId();
        }
        eventId.setId(id);
    }

    @DynamoDBHashKey
    public String getLogEntityId() {
        return eventId != null? eventId.getLogEntityId() : null;
    }

    public void setLogEntityId(String logEntityId) {
        if (eventId == null) {
            eventId = new EventId();
        }
        eventId.setLogEntityId(logEntityId);
    }

    @DynamoDBAttribute
    public String getEntry() {
        return entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        Event event = (Event) o;
        return !(eventId != null ? !eventId.equals(event.eventId) : event.eventId != null);
    }

    @Override
    public int hashCode() {
        return eventId != null ? eventId.hashCode() : 0;
    }
}